### ISSUE TITLE
Domain files are still using version 2

### ISSUE THREAD

**Issue by hongbo-miao** [RasaHQ/conversational-ai-course-3.x#1]
The domain files is still using version 2.
It would be great to upgrade to version 3, thanks! 😃

https://github.com/RasaHQ/conversational-ai-course-3.x/blob/5eff0475702c2c750b668397c2554b8c0160968e/video-09-1-basic-forms/domain.yml#L1

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Fixed via https://github.com/RasaHQ/conversational-ai-course-3.x/pull/2
